# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoapp
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'

pod 'Pushwoosh'

end
